server:
  port: 9900

spring:
  application:
    name: consumer

eureka:
  instance:
    instance-id: consumer
  client:
    fetch-registry: true
#    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8800/eureka

feign:
  hystrix:
    enabled: true